version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.28
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
  hotrod:
    image: jaegertracing/example-hotrod:1.28
    ports:
      - "8080-8083:8080-8083"
    environment:
      - JAEGER_AGENT_HOST=jaeger
    command: all